---
api_token: pat.xUh5vopuSpyc808GM3_cgA.634749209469cd663c81172a.eU8cGXhdTWNQspQrbUy2

account_id: xUh5vopuSpyc808GM3_cgA

org_id: Automation

project_id: Ansibler

token_name: ansible-created-it00445

delegate_name: ansible-delegate6445445